modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="irisflw"
version="${file.jarVersion}"
displayName="Oculus Flywheel Compat"
logoFile="icon.png"
authors="Leon"
description='''
Enable FlyWheel instancing optimization when use custom shaders.
'''
[[dependencies.irisflw]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.irisflw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.irisflw]]
    modId="oculus"
    mandatory=true
    versionRange="[1.4,)"
    ordering="NONE"
    side="CLIENT"

